/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DonationId = IDL.Nat;
export const DonationStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inTransit' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Donation = IDL.Record({
  'id' : DonationId,
  'status' : DonationStatus,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'assignedTo' : IDL.Opt(UserId),
  'donorId' : UserId,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'pickupAddress' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'pickupWindowEnd' : Timestamp,
  'acceptedBy' : IDL.Opt(UserId),
  'pickupWindowStart' : Timestamp,
  'contactPhone' : IDL.Text,
  'foodType' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateDonationRequest = IDL.Record({
  'imageBlob' : IDL.Opt(ExternalBlob),
  'unit' : IDL.Text,
  'pickupAddress' : IDL.Text,
  'quantity' : IDL.Nat,
  'pickupWindowEnd' : Timestamp,
  'pickupWindowStart' : Timestamp,
  'contactPhone' : IDL.Text,
  'foodType' : IDL.Text,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'ngo' : IDL.Null,
  'admin' : IDL.Null,
  'deliveryAgent' : IDL.Null,
  'donor' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'status' : UserStatus,
  'orgName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'phone' : IDL.Text,
});
export const Analytics = IDL.Record({
  'assigned' : IDL.Nat,
  'cancelled' : IDL.Nat,
  'expired' : IDL.Nat,
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'rejected' : IDL.Nat,
  'totalDonations' : IDL.Nat,
  'accepted' : IDL.Nat,
  'totalQuantity' : IDL.Nat,
  'activeNGOs' : IDL.Nat,
});
export const RegisterUserRequest = IDL.Record({
  'orgName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : UserRole,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptDonation' : IDL.Func([DonationId, IDL.Opt(IDL.Text)], [Donation], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignDeliveryAgent' : IDL.Func([DonationId, UserId], [Donation], []),
  'cancelDonation' : IDL.Func([DonationId], [Donation], []),
  'createDonation' : IDL.Func([CreateDonationRequest], [Donation], []),
  'deactivateUser' : IDL.Func([UserId], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getAssignedPickups' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getDonationsByDonor' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getPendingDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPickupCompleted' : IDL.Func(
      [DonationId, IDL.Opt(IDL.Text)],
      [Donation],
      [],
    ),
  'reactivateUser' : IDL.Func([UserId], [], []),
  'registerUser' : IDL.Func([RegisterUserRequest], [User], []),
  'rejectDonation' : IDL.Func([DonationId, IDL.Opt(IDL.Text)], [Donation], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DonationId = IDL.Nat;
  const DonationStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inTransit' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Donation = IDL.Record({
    'id' : DonationId,
    'status' : DonationStatus,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'assignedTo' : IDL.Opt(UserId),
    'donorId' : UserId,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'pickupAddress' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'pickupWindowEnd' : Timestamp,
    'acceptedBy' : IDL.Opt(UserId),
    'pickupWindowStart' : Timestamp,
    'contactPhone' : IDL.Text,
    'foodType' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateDonationRequest = IDL.Record({
    'imageBlob' : IDL.Opt(ExternalBlob),
    'unit' : IDL.Text,
    'pickupAddress' : IDL.Text,
    'quantity' : IDL.Nat,
    'pickupWindowEnd' : Timestamp,
    'pickupWindowStart' : Timestamp,
    'contactPhone' : IDL.Text,
    'foodType' : IDL.Text,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'ngo' : IDL.Null,
    'admin' : IDL.Null,
    'deliveryAgent' : IDL.Null,
    'donor' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'status' : UserStatus,
    'orgName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'phone' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'assigned' : IDL.Nat,
    'cancelled' : IDL.Nat,
    'expired' : IDL.Nat,
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'rejected' : IDL.Nat,
    'totalDonations' : IDL.Nat,
    'accepted' : IDL.Nat,
    'totalQuantity' : IDL.Nat,
    'activeNGOs' : IDL.Nat,
  });
  const RegisterUserRequest = IDL.Record({
    'orgName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : UserRole,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptDonation' : IDL.Func(
        [DonationId, IDL.Opt(IDL.Text)],
        [Donation],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignDeliveryAgent' : IDL.Func([DonationId, UserId], [Donation], []),
    'cancelDonation' : IDL.Func([DonationId], [Donation], []),
    'createDonation' : IDL.Func([CreateDonationRequest], [Donation], []),
    'deactivateUser' : IDL.Func([UserId], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getAssignedPickups' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getDonationsByDonor' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getPendingDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPickupCompleted' : IDL.Func(
        [DonationId, IDL.Opt(IDL.Text)],
        [Donation],
        [],
      ),
    'reactivateUser' : IDL.Func([UserId], [], []),
    'registerUser' : IDL.Func([RegisterUserRequest], [User], []),
    'rejectDonation' : IDL.Func(
        [DonationId, IDL.Opt(IDL.Text)],
        [Donation],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };