/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'assigned' : bigint,
  'cancelled' : bigint,
  'expired' : bigint,
  'pending' : bigint,
  'completed' : bigint,
  'rejected' : bigint,
  'totalDonations' : bigint,
  'accepted' : bigint,
  'totalQuantity' : bigint,
  'activeNGOs' : bigint,
}
export interface CreateDonationRequest {
  'imageBlob' : [] | [ExternalBlob],
  'unit' : string,
  'pickupAddress' : string,
  'quantity' : bigint,
  'pickupWindowEnd' : Timestamp,
  'pickupWindowStart' : Timestamp,
  'contactPhone' : string,
  'foodType' : string,
}
export interface Donation {
  'id' : DonationId,
  'status' : DonationStatus,
  'imageBlob' : [] | [ExternalBlob],
  'assignedTo' : [] | [UserId],
  'donorId' : UserId,
  'createdAt' : Timestamp,
  'unit' : string,
  'pickupAddress' : string,
  'notes' : [] | [string],
  'quantity' : bigint,
  'pickupWindowEnd' : Timestamp,
  'acceptedBy' : [] | [UserId],
  'pickupWindowStart' : Timestamp,
  'contactPhone' : string,
  'foodType' : string,
}
export type DonationId = bigint;
export type DonationStatus = { 'assigned' : null } |
  { 'cancelled' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inTransit' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type ExternalBlob = Uint8Array;
export interface RegisterUserRequest {
  'orgName' : [] | [string],
  'name' : string,
  'role' : UserRole,
  'phone' : string,
}
export type Timestamp = bigint;
export interface User {
  'id' : Principal,
  'status' : UserStatus,
  'orgName' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'phone' : string,
}
export type UserId = Principal;
export type UserRole = { 'ngo' : null } |
  { 'admin' : null } |
  { 'deliveryAgent' : null } |
  { 'donor' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'inactive' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptDonation' : ActorMethod<[DonationId, [] | [string]], Donation>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignDeliveryAgent' : ActorMethod<[DonationId, UserId], Donation>,
  'cancelDonation' : ActorMethod<[DonationId], Donation>,
  'createDonation' : ActorMethod<[CreateDonationRequest], Donation>,
  'deactivateUser' : ActorMethod<[UserId], undefined>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getAssignedPickups' : ActorMethod<[], Array<Donation>>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDonations' : ActorMethod<[], Array<Donation>>,
  'getDonationsByDonor' : ActorMethod<[], Array<Donation>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getPendingDonations' : ActorMethod<[], Array<Donation>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markPickupCompleted' : ActorMethod<[DonationId, [] | [string]], Donation>,
  'reactivateUser' : ActorMethod<[UserId], undefined>,
  'registerUser' : ActorMethod<[RegisterUserRequest], User>,
  'rejectDonation' : ActorMethod<[DonationId, [] | [string]], Donation>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];