/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RegisterUserRequest {
    orgName?: string;
    name: string;
    role: UserRole;
    phone: string;
}
export type Timestamp = bigint;
export interface User {
    id: Principal;
    status: UserStatus;
    orgName?: string;
    name: string;
    createdAt: bigint;
    role: UserRole;
    phone: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CreateDonationRequest {
    imageBlob?: ExternalBlob;
    unit: string;
    pickupAddress: string;
    quantity: bigint;
    pickupWindowEnd: Timestamp;
    pickupWindowStart: Timestamp;
    contactPhone: string;
    foodType: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserId = Principal;
export interface Donation {
    id: DonationId;
    status: DonationStatus;
    imageBlob?: ExternalBlob;
    assignedTo?: UserId;
    donorId: UserId;
    createdAt: Timestamp;
    unit: string;
    pickupAddress: string;
    notes?: string;
    quantity: bigint;
    pickupWindowEnd: Timestamp;
    acceptedBy?: UserId;
    pickupWindowStart: Timestamp;
    contactPhone: string;
    foodType: string;
}
export interface Analytics {
    assigned: bigint;
    cancelled: bigint;
    expired: bigint;
    pending: bigint;
    completed: bigint;
    rejected: bigint;
    totalDonations: bigint;
    accepted: bigint;
    totalQuantity: bigint;
    activeNGOs: bigint;
}
export type DonationId = bigint;
export enum DonationStatus {
    assigned = "assigned",
    cancelled = "cancelled",
    expired = "expired",
    pending = "pending",
    completed = "completed",
    inTransit = "inTransit",
    rejected = "rejected",
    accepted = "accepted"
}
export enum UserRole {
    ngo = "ngo",
    admin = "admin",
    deliveryAgent = "deliveryAgent",
    donor = "donor"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    inactive = "inactive"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptDonation(donationId: DonationId, notes: string | null): Promise<Donation>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignDeliveryAgent(donationId: DonationId, agentId: UserId): Promise<Donation>;
    cancelDonation(donationId: DonationId): Promise<Donation>;
    createDonation(req: CreateDonationRequest): Promise<Donation>;
    deactivateUser(userId: UserId): Promise<void>;
    getAllUsers(): Promise<Array<User>>;
    getAnalytics(): Promise<Analytics>;
    getAssignedPickups(): Promise<Array<Donation>>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDonations(): Promise<Array<Donation>>;
    getDonationsByDonor(): Promise<Array<Donation>>;
    getMyProfile(): Promise<User | null>;
    getPendingDonations(): Promise<Array<Donation>>;
    isCallerAdmin(): Promise<boolean>;
    markPickupCompleted(donationId: DonationId, notes: string | null): Promise<Donation>;
    reactivateUser(userId: UserId): Promise<void>;
    registerUser(req: RegisterUserRequest): Promise<User>;
    rejectDonation(donationId: DonationId, notes: string | null): Promise<Donation>;
}
import type { CreateDonationRequest as _CreateDonationRequest, Donation as _Donation, DonationId as _DonationId, DonationStatus as _DonationStatus, ExternalBlob as _ExternalBlob, RegisterUserRequest as _RegisterUserRequest, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserRole as _UserRole, UserRole__1 as _UserRole__1, UserStatus as _UserStatus, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptDonation(arg0: DonationId, arg1: string | null): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptDonation(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptDonation(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignDeliveryAgent(arg0: DonationId, arg1: UserId): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDeliveryAgent(arg0, arg1);
                return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDeliveryAgent(arg0, arg1);
            return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelDonation(arg0: DonationId): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelDonation(arg0);
                return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelDonation(arg0);
            return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDonation(arg0: CreateDonationRequest): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.createDonation(await to_candid_CreateDonationRequest_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDonation(await to_candid_CreateDonationRequest_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getAssignedPickups(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedPickups();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedPickups();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonations();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonations();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationsByDonor(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationsByDonor();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationsByDonor();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDonations();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDonations();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markPickupCompleted(arg0: DonationId, arg1: string | null): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.markPickupCompleted(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPickupCompleted(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async reactivateUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactivateUser(arg0);
            return result;
        }
    }
    async registerUser(arg0: RegisterUserRequest): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_RegisterUserRequest_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_User_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_RegisterUserRequest_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_User_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectDonation(arg0: DonationId, arg1: string | null): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDonation(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDonation(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Donation_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DonationStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationStatus): DonationStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_Donation_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donation): Promise<Donation> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_UserRole__1_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_User_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DonationId;
    status: _DonationStatus;
    imageBlob: [] | [_ExternalBlob];
    assignedTo: [] | [_UserId];
    donorId: _UserId;
    createdAt: _Timestamp;
    unit: string;
    pickupAddress: string;
    notes: [] | [string];
    quantity: bigint;
    pickupWindowEnd: _Timestamp;
    acceptedBy: [] | [_UserId];
    pickupWindowStart: _Timestamp;
    contactPhone: string;
    foodType: string;
}): Promise<{
    id: DonationId;
    status: DonationStatus;
    imageBlob?: ExternalBlob;
    assignedTo?: UserId;
    donorId: UserId;
    createdAt: Timestamp;
    unit: string;
    pickupAddress: string;
    notes?: string;
    quantity: bigint;
    pickupWindowEnd: Timestamp;
    acceptedBy?: UserId;
    pickupWindowStart: Timestamp;
    contactPhone: string;
    foodType: string;
}> {
    return {
        id: value.id,
        status: from_candid_DonationStatus_n11(_uploadFile, _downloadFile, value.status),
        imageBlob: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.imageBlob)),
        assignedTo: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.assignedTo)),
        donorId: value.donorId,
        createdAt: value.createdAt,
        unit: value.unit,
        pickupAddress: value.pickupAddress,
        notes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.notes)),
        quantity: value.quantity,
        pickupWindowEnd: value.pickupWindowEnd,
        acceptedBy: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.acceptedBy)),
        pickupWindowStart: value.pickupWindowStart,
        contactPhone: value.contactPhone,
        foodType: value.foodType
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    status: _UserStatus;
    orgName: [] | [string];
    name: string;
    createdAt: bigint;
    role: _UserRole;
    phone: string;
}): {
    id: Principal;
    status: UserStatus;
    orgName?: string;
    name: string;
    createdAt: bigint;
    role: UserRole;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n25(_uploadFile, _downloadFile, value.status),
        orgName: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.orgName)),
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n27(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    cancelled: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inTransit: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): DonationStatus {
    return "assigned" in value ? DonationStatus.assigned : "cancelled" in value ? DonationStatus.cancelled : "expired" in value ? DonationStatus.expired : "pending" in value ? DonationStatus.pending : "completed" in value ? DonationStatus.completed : "inTransit" in value ? DonationStatus.inTransit : "rejected" in value ? DonationStatus.rejected : "accepted" in value ? DonationStatus.accepted : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "inactive" in value ? UserStatus.inactive : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ngo: null;
} | {
    admin: null;
} | {
    deliveryAgent: null;
} | {
    donor: null;
}): UserRole {
    return "ngo" in value ? UserRole.ngo : "admin" in value ? UserRole.admin : "deliveryAgent" in value ? UserRole.deliveryAgent : "donor" in value ? UserRole.donor : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n23(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donation>): Promise<Array<Donation>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Donation_n9(_uploadFile, _downloadFile, x)));
}
async function to_candid_CreateDonationRequest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateDonationRequest): Promise<_CreateDonationRequest> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_RegisterUserRequest_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterUserRequest): _RegisterUserRequest {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageBlob?: ExternalBlob;
    unit: string;
    pickupAddress: string;
    quantity: bigint;
    pickupWindowEnd: Timestamp;
    pickupWindowStart: Timestamp;
    contactPhone: string;
    foodType: string;
}): Promise<{
    imageBlob: [] | [_ExternalBlob];
    unit: string;
    pickupAddress: string;
    quantity: bigint;
    pickupWindowEnd: _Timestamp;
    pickupWindowStart: _Timestamp;
    contactPhone: string;
    foodType: string;
}> {
    return {
        imageBlob: value.imageBlob ? candid_some(await to_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.imageBlob)) : candid_none(),
        unit: value.unit,
        pickupAddress: value.pickupAddress,
        quantity: value.quantity,
        pickupWindowEnd: value.pickupWindowEnd,
        pickupWindowStart: value.pickupWindowStart,
        contactPhone: value.contactPhone,
        foodType: value.foodType
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orgName?: string;
    name: string;
    role: UserRole;
    phone: string;
}): {
    orgName: [] | [string];
    name: string;
    role: _UserRole;
    phone: string;
} {
    return {
        orgName: value.orgName ? candid_some(value.orgName) : candid_none(),
        name: value.name,
        role: to_candid_UserRole_n35(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    ngo: null;
} | {
    admin: null;
} | {
    deliveryAgent: null;
} | {
    donor: null;
} {
    return value == UserRole.ngo ? {
        ngo: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.deliveryAgent ? {
        deliveryAgent: null
    } : value == UserRole.donor ? {
        donor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
